# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  	- cron: "0 0 */1 * *"
 
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Update Python Script
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python feed_tistory.py
    - name: Update README.md fileQ
      run: |
        git pull
        git add .
        git config --local user.email "2523@naver.com"
        git config --local user.name "madmax490500"
        git commit -m "Update README.mdQ"
        git push
